import Head from 'next/head'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'

export default function Home({ results }) {
  return (
    <main>
      <Head>
        <title>Hulu</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/icon.png' />
      </Head>

      {/* header */}

      <Header />

      {/* Nav */}
      <Nav />

      {/* Results */}
      <Results results={results} />
    </main>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.Trending.url
    }`
  ).then((res) => res.json())

  return {
    props: {
      results: request?.results,
    },
  }
}
