import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Hulu</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/icon.png' />
      </Head>

      {/* header */}
      <Header />

      {/* Nav */}
      <Nav />

      {/* Results */}
      <Results />
    </>
  )
}
